[project]
name = "file-read-assigment"
version = "0.1.0"
description = "Assigment for the course 'Programming 2' at the SRH Hochschule Berlin"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.4.0",
]
